### ISSUE TITLE
PaRe for general R package developers

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/DependencyReviewer#13]
Although we of course will be using the package in darwin and ohdsi, it would be nice to make sure it is flexible to the general R package developer. @mvankessel-EMC I guess the first step is making sure functions in PaRe are not named with darwin/ ohdsi, but also that other users can easily specify their own dependency whitelist and code style (e.g. if they are using only snake_case, etc)

**Comment by mvankessel-EMC** [comment]
I've already taken steps in the dev branch commit: 91ecfd1c65493555b57cc29dfb219c462745e9aa. `darwinLintPackage` has been renamed to `lintPackage` package for instance.
